### ISSUE TITLE
Storage for opentelemetry-ebpf-profiler coredump test suite

### ISSUE THREAD

**Issue by christos68k** [open-telemetry/community#2398] opened 2024-10-15 15:07 UTC
As part of the Elastic Universal Profiling [donation](https://github.com/open-telemetry/community/issues/1918) to OpenTelemetry, the coredump files that comprise the coredump test [suite](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/tree/main/tools/coredump) (which is the main testing mechanism for all the different language runtime unwinders) need to be transferred to OpenTelemetry.

Currently, they are sitting in an Elastic S3 bucket and are inaccessible to the public: 618 objects each individually [compressed](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/tree/main/tools/zstpak/lib) with a total size of ~2.8GB.

CC: @tigrannajaryan

**Comment by trask** [comment] 2024-10-16 23:51
We may be able to set you up with something similar in Oracle Cloud where the [CNCF has a lot of credits](https://www.cncf.io/blog/2024/02/02/oracle-oci-credits-are-now-available-to-cncf-projects-here-is-what-you-need-to-know/).

cc @austinlparker as the Admin for our Oracle Cloud Account (https://github.com/open-telemetry/community/blob/main/assets.md#oracle-cloud-account)

**Comment by austinlparker** [comment] 2024-10-16 23:53
Yeah we can do this in our OCI instance. Feel free to reach out on Slack to discuss the details.

**Comment by austinlparker** [comment] 2024-10-17 16:55
I've created a bucket with a public (read) access URL, as well as an account and management keys for it. The credentials and information are in a new 1Password vault that the following individuals have been invited to -

[christos.kalkanis@elastic.co](mailto:christos.kalkanis@elastic.co)
[timo.teras@iki.fi](mailto:timo.teras@iki.fi)
[florian.lehner@elastic.co](mailto:florian.lehner@elastic.co)
[tim.ruhsen@elastic.co](mailto:tim.ruhsen@elastic.co)
[joel@zyantific.com](mailto:joel@zyantific.com)

**Comment by christos68k** [comment] 2024-10-17 17:01
@felixge @petethepig please reach out to @austinlparker in order to be added.

**Comment by florianl** [comment] 2024-10-21 08:15
I did accept the invite and did setup 2FA for my 1Password account, but there are not shared vaults. Is there something I have to do, besides accepting the invite to get access to credentials for the OCI instance?

**Comment by trask** [comment] 2024-10-22 16:27
@tylerbenson mentioned another option for storing the coredump test suite in slack: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage

this seems like a nice option which would also preserve history, what do you all think?

it looks like the large files could be added directly to the opentelemetry-ebpf-profiler repository, or if there are concerns we could create a separate repo for them under the open-telemetry org

**Comment by christos68k** [comment] 2024-10-22 16:36
> @tylerbenson mentioned another option for storing the coredump test suite in slack: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage
> 
> this seems like a nice option which would also preserve history, what do you all think?
> 
> it looks like the large files could be added directly to the opentelemetry-ebpf-profiler repository, or if there are concerns we could create a separate repo for them under the open-telemetry org

The proposed Oracle Cloud solution exposes an S3-compatible API which would require minimal engineering effort from us to adapt, as we're already pushing to S3. 

Besides additional engineering effort, possible issues I see with git-lfs are [storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) and [bandwidth](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage) limits which are quite conservative.

**Comment by yurishkuro** [comment] 2024-10-22 16:38
> it looks like the large files could be added directly to the opentelemetry-ebpf-profiler repository, or if there are concerns we could create a separate repo for them under the open-telemetry org

if you go with Git LFS approach I would recommend a separate repo included as a submodule.

**Comment by austinlparker** [comment] 2024-10-22 17:30
@florianl hey - you wouldn't have seen shared vaults until i confirmed your account, which I did yesterday afternoon. please check again.

**Comment by rockdaboot** [comment] 2024-10-22 17:47
@austinlparker I can not find an invitation (also not in the spam folder). Can you check or invite again?

**Comment by florianl** [comment] 2024-10-23 08:19
> [..]  i confirmed your account, which I did yesterday afternoon. please check again.

Thanks @austinlparker - I can see and access now the `opentelemetry-profiling` vault. :+1:

**Comment by trask** [comment] 2024-11-05 21:34
@christos68k @florianl @rockdaboot is everything good here, can we close the issue? thanks!

**Comment by florianl** [comment] 2024-11-06 08:12
I have verified that the provided credentials work for me using the oci CLI tooling. So closing this issue is fine with me.

**Closed** 2024-11-06 16:29 UTC
Labels: area/project-infra
