### ISSUE TITLE
Rename master to main for all OpenTelemetry repos

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#578] opened 2020-12-01 03:51 UTC
Earlier this year, GitHub announced its plan to [rename](https://github.com/github/renaming/blob/main/README.md) the default branch on repos from 'master' to 'main'. As a fast-growing open source project, we're looking to constantly increase participation and diversity of contributors and contributions to OpenTelemetry. In keeping with being an inclusive and welcoming community, I propose we change the default branch name to 'main' for all OpenTelemetry repos before we ship our next big 'stable' release.

cc: @SergeyKanzhelev @tedsuo

**Comment by bhs** [comment] 2020-12-01 04:07
This was raised earlier in the year as #402. The [last comment](https://github.com/open-telemetry/community/issues/402#issuecomment-696242852) there was:

>We talked about this in the Maintainers meeting today - the maintainers generally seemed like waiting until the automatic github renaming occurred later this year was sufficient. If we decide it must happen earlier, I don't foresee a lot of resistance against that kind of initiative.

**Comment by alolita** [comment] 2020-12-01 04:17
@bhs Thanks for linking back to the earlier issue. I can close this issue if we want to use #402 instead.

**Comment by bhs** [comment] 2020-12-01 04:24
Duplicate of #402

**Closed by bhs** 2020-12-01 04:24 UTC
