### ISSUE TITLE
REQUEST: New membership for <your-GH-handle>

### ISSUE THREAD

**Issue by Flarna** [open-telemetry/community#602] opened 2021-01-14 14:45 UTC
### GitHub Username

@Flarna

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan 
- @obecny 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+author%3AFlarna

**Comment by dyladan** [comment] 2021-01-14 14:46
Duplicate of #601

**Closed by dyladan** 2021-01-14 14:46 UTC
Labels: area/github-membership

**Comment by Flarna** [comment] 2021-01-14 14:58
Ups, got a 404 and retried...
