### ISSUE TITLE
Make jmacd an OTEPs maintainer (need more OTEPs maintainers)

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/community#406] opened 2020-07-02 22:51 UTC
See https://github.com/open-telemetry/community/issues/329

I would like to nominate myself as a new OTEPs maintainer since we have not finished the per-signal codeownership changes. I am not sure if the community rules allow this, so I'm filing an issue.

The OTEPs that should merge are 
https://github.com/open-telemetry/oteps/pull/108
https://github.com/open-telemetry/oteps/pull/113
https://github.com/open-telemetry/oteps/pull/117
https://github.com/open-telemetry/oteps/pull/118
https://github.com/open-telemetry/oteps/pull/119

**Comment by carlosalberto** [comment] 2020-07-09 21:10
Sounds great to me.

**Comment by bogdandrutu** [comment] 2020-07-14 19:52
The rule says that only TC members can be maintainers of oteps, so this request should be to make you a TC member which can be discussed in a TC meeting

**Comment by bogdandrutu** [comment] 2020-07-14 19:54
Also 119 is not ready because it does not have enough approvers.

**Comment by bogdandrutu** [comment] 2020-07-14 19:58
The only PR that is ready to be merged is open-telemetry/oteps#108 which has a comment at the end that more work is coming, so I think the problem is not the maintainers, but reviews.

<img width="912" alt="Screen Shot 2020-07-14 at 12 56 47 PM" src="https://user-images.githubusercontent.com/1373887/87470502-b690c880-c5d1-11ea-94b1-9e6dd50a4ae6.png">

**Comment by lizthegrey** [comment] 2020-07-21 18:05
Agree, this is a TC decision (and also involves necessarily membership in the TC)

**Closed** 2020-09-17 07:04 UTC
