### ISSUE TITLE
Donation fpr OpenTelemetry

### ISSUE THREAD

**Issue by JennyScripts3** [open-telemetry/community#1779] opened 2023-11-07 12:38 UTC
Hello

On the 26th october we hosted our annual customer event Puzzle up! at Wankdorf Stadium, and we conducted a buzzer action to raise donations for each of our vision elements:

we care: Hörschatz
we invent: NetAP
we contribute: Open Telemetry

During this buzzer action, we collected donations totaling 1,050 Swiss Francs for Open Telemetry. We will transfer the money as soon as you provide us with the payment/account details. Can someone help us?

Thank you very much & best regards
Jenny from Puzzle ITC

**Comment by trask** [comment] 2023-11-07 15:45
(closing as duplicate of #1780)

**Closed by trask** 2023-11-07 15:45 UTC
